config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :systems
  resources :engagements
  root :to => redirect('/systems')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/engagement.rb
class Engagement < ApplicationRecord
    has_many :systems

    validates :code, :presence => true
    validates :client, :presence => true

    def to_s
        code
    end

end

app/models/system.rb
class System < ApplicationRecord
  belongs_to :engagement

  enum status: { open: 1, wip: 2, done: 3, blocked: 4 }

  validates :hostname, :presence => true
  validates :status, :presence => true

  def to_s
    hostname
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/engagements_controller.rb
class EngagementsController < ApplicationController
  before_action :set_engagement, only: [:show, :edit, :update, :destroy]

  # GET /engagements
  # GET /engagements.json
  def index
    @engagements = Engagement.all
  end

  # GET /engagements/1
  # GET /engagements/1.json
  def show
  end

  # GET /engagements/new
  def new
    @engagement = Engagement.new
  end

  # GET /engagements/1/edit
  def edit
  end

  # POST /engagements
  # POST /engagements.json
  def create
    @engagement = Engagement.new(engagement_params)

    respond_to do |format|
      if @engagement.save
        format.html { redirect_to @engagement, notice: 'Engagement was successfully created.' }
        format.json { render :show, status: :created, location: @engagement }
      else
        format.html { render :new }
        format.json { render json: @engagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engagements/1
  # PATCH/PUT /engagements/1.json
  def update
    respond_to do |format|
      if @engagement.update(engagement_params)
        format.html { redirect_to @engagement, notice: 'Engagement was successfully updated.' }
        format.json { render :show, status: :ok, location: @engagement }
      else
        format.html { render :edit }
        format.json { render json: @engagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engagements/1
  # DELETE /engagements/1.json
  def destroy
    @engagement.destroy
    respond_to do |format|
      format.html { redirect_to engagements_url, notice: 'Engagement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engagement
      @engagement = Engagement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engagement_params
      params.require(:engagement).permit(:code, :client)
    end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  before_action :set_system, only: [:show, :edit, :update, :destroy]

  # GET /systems
  # GET /systems.json
  def index
    @systems = System.all
  end

  # GET /systems/1
  # GET /systems/1.json
  def show
  end

  # GET /systems/new
  def new
    @system = System.new
  end

  # GET /systems/1/edit
  def edit
  end

  # POST /systems
  # POST /systems.json
  def create
    @system = System.new(system_params)

    respond_to do |format|
      if @system.save
        format.html { redirect_to @system, notice: 'System was successfully created.' }
        format.json { render :show, status: :created, location: @system }
      else
        format.html { render :new }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /systems/1
  # PATCH/PUT /systems/1.json
  def update
    respond_to do |format|
      if @system.update(system_params)
        format.html { redirect_to @system, notice: 'System was successfully updated.' }
        format.json { render :show, status: :ok, location: @system }
      else
        format.html { render :edit }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.json
  def destroy
    @system.destroy
    respond_to do |format|
      format.html { redirect_to systems_url, notice: 'System was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system
      @system = System.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_params
      params.require(:system).permit(:hostname, :lead, :notes, :summary, :status, :engagement_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engagements_helper.rb
module EngagementsHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/engagements/_form.html.erb
<%= form_with(model: engagement, local: true) do |form| %>
  <% if engagement.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(engagement.errors.count, "error") %> prohibited this engagement from being saved:</h3>

      <ul>
      <% engagement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, class: "uk-input uk-form-width-large", placeholder: "NIKE-03-2020" %>
  </div>

  <div class="field">
    <%= form.label :client %>
    <%= form.text_field :client, class: "uk-input uk-form-width-large", placeholder: "Nike" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', :class => "uk-button uk-button-primary" %>
  </div>
<% end %>

app/views/engagements/edit.html.erb
<h3>Editing Engagement</h1>

<%= render 'form', engagement: @engagement %>

app/views/engagements/index.html.erb
<p id="notice"><%= notice %></p>

<div style="display: flex; justify-content: space-between">
  <div>
    <h3>Engagements</h1>
  </div>
  <div>
    <%= link_to 'New Engagement', new_engagement_path, class: "uk-button uk-button-primary" %>
  </div>
</div>

<p class="uk-text-meta">
  All the incident response investigations we've worked on for clients
</p>

<table class="uk-table uk-table-divider uk-table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engagements.each do |engagement| %>
      <tr>
        <td><%= engagement.code %></td>
        <td><%= engagement.client %></td>
        <td><%= link_to 'Edit', edit_engagement_path(engagement) %></td>
        <td><%= link_to 'Delete', engagement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/engagements/new.html.erb
<h3>New Engagement</h1>

<%= render 'form', engagement: @engagement %>

app/views/engagements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @engagement.code %>
</p>

<p>
  <strong>Client:</strong>
  <%= @engagement.client %>
</p>

<%= link_to 'Edit', edit_engagement_path(@engagement) %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Live Response Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="uk-navbar-container" uk-navbar>
      <div class="uk-navbar-left">
          <ul class="uk-navbar-nav">
            <li><%=link_to "Engagements", engagements_path%></li>
            <li><%=link_to "Systems", systems_path%></li>
          </ul>
      </div>
    </nav>
    <div style="margin: 33px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/systems/_form.html.erb
<%= form_with(model: system, local: true) do |form| %>
  <% if system.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(system.errors.count, "error") %> prohibited this system from being saved:</h2>

      <ul>
      <% system.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hostname %>
    <%= form.text_field :hostname, class: "uk-input uk-form-width-large", placeholder: "WIN-2322" %>
  </div>

  <div class="field">
    <%= form.label :lead %>
    <%= form.text_area :lead, class: "uk-textarea uk-form-width-large", size: "75x7", placeholder: "osquery indicates mimikatz was executed" %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, class: "uk-textarea uk-form-width-large", size:"75x7", placeholder: "- SIEM logs indicate the attacker uploaded files from the Desktop to a Dropbox account" %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: "uk-textarea uk-form-width-large", size: "75x7", placeholder: "Financial data was likely lost. Escalate this into an incident" %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, System.statuses.keys.to_a, {}, {:class => 'uk-select uk-form-width-large'} %>
  </div>

  <div class="field">
    <%= form.label :engagement_id %>
    <%= form.collection_select(:engagement_id, Engagement.all, :id, :code, {:prompt => 'Select the engagement', :selected => @system.engagement_id}, {:class => 'uk-select uk-form-width-large'}) =%>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', :class => "uk-button uk-button-primary" %>
  </div>
<% end %>

app/views/systems/edit.html.erb
<h3>Editing System <%= @system.hostname =%></h1>

<%= render 'form', system: @system %>

app/views/systems/index.html.erb
<p id="notice"><%= notice %></p>

<div style="display: flex; justify-content: space-between">
  <div>
    <h3>Systems</h1>
  </div>
  <div>
    <%= link_to 'New System', new_system_path, class: "uk-button uk-button-primary" %>
  </div>
</div>

<p class="uk-text-meta">
  All the computers that we've forensically analyzed
</p>

<table class="uk-table uk-table-divider uk-table-hover">
  <thead>
    <tr>
      <th>Hostname</th>
      <th>Created</th>
      <th>Lead</th>
      <th>Summary</th>
      <th>Status</th>
      <th>Engagement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @systems.each do |system| %>
      <tr>
        <td><%= system.hostname %></td>
        <td><%= system.created_at %></td>
        <td><%= system.lead %></td>
        <td><%= system.summary %></td>
        <td><%= system.status %></td>
        <td><%= system.engagement %></td>
        <td><%= link_to 'Edit', edit_system_path(system) %></td>
        <td><%= link_to 'Delete', system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/systems/new.html.erb
<h3>New System</h1>

<%= render 'form', system: @system %>

app/views/systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hostname:</strong>
  <%= @system.hostname %>
</p>

<p>
  <strong>Lead:</strong>
  <%= @system.lead %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @system.notes %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @system.summary %>
</p>

<p>
  <strong>Status:</strong>
  <%= @system.status %>
</p>

<p>
  <strong>Engagement:</strong>
  <%= @system.engagement %>
</p>

<%= link_to 'Edit', edit_system_path(@system) %> |